### ISSUE TITLE
Contao 5.4: Beim Öffnen der ersten Newsebene gibt es eine Fehlermeldung 

### ISSUE THREAD

**Issue by jankout** [hschottm/tags#102]
Wenn ich auf die erste Ebene eines Newsbeitrag gelangen will, wird mir folgende Fehlermeldung angezeigt. Wie kann ich es beseitigen? 

`Class "Hschottm\TagsBundle\EventListener\DataContainer\ContentModel" not found`

**Comment by hschottm** [comment]
Ein fehlender Import, ich habe gerade eine neue Version 5.0.3 auf Packagist gepackt.

**Comment by jankout** [comment]
super. Danke. Das funktioniert nun. Allerdings gibt es noch einen Fehler bei TagCloud. Das verursacht folgenden Fehler

`[2024-11-22T01:10:42.822052+01:00] request.CRITICAL: Uncaught PHP Exception Error: "Call to a member function get() on null" at TagHelper.php line 87 {"exception":"[object] (Error(code: 0): Call to a member function get() on null at /homepages/35/d432404500/htdocs/contao5/vendor/hschottm/tags/src/Resources/contao/classes/TagHelper.php:87)"} `

**Comment by hschottm** [comment]
Behoben, 5.0.4 ist raus

**Comment by jankout** [comment]
Vielen Dank! Jetzt läuft alles richtig.
