### ISSUE TITLE
Fehler: "Das Feld Auszeichnungsfilter darf höchstens 255 Zeichen haben"

### ISSUE THREAD

**Issue by AgentCT** [hschottm/tags#16]
Bei der Verwendung der "Nachrichtenliste" erhalten ich den Fehler "Das Feld Auszeichnungsfilter darf höchstens 255 Zeichen haben.", wenn ich viele Filterbegriffe angebe.

Kann das Feld bitte beim nächsten Update auf ein größeres Feld umgestellt werden?

Vielen Dank
Stefan

**Comment by hschottm** [comment]
Fixed in 82b92d555dc0c7c71b4ed431bc175110bbbf3a95

**Comment by AgentCT** [comment]
Danke schön!

**Comment by AgentCT** [comment]
Leider hat der Fix den Fehler #16 nicht vollständig korrigiert.

Das Problem ist leider immer noch vorhanden. Das Problem habe ich u.a. in der tl_module.php (Zeile 136 & 137) gefunden. Leider war mein Korrekturansatz damit offenbar noch nicht vollständig.

Bei der Eintragung von Werten über 255 Zeichen werden nunmehr, die darüber liegenden Zeichen abgeschnitten und nicht gespeichert.

**Comment by hschottm** [comment]
Sorry, das hab ich übersehen. Da habe ich dann ein Feld zu wenig geändert.
Auch wenn es nicht ganz sauber ist, ich habe das jetzt einfach nur als neuen build ins ER eingespielt.

Fixed in 0521ef293bb58e8fea9eb09471cc61d41632ecb5

**Comment by AgentCT** [comment]
Kein Problem, man kann es sich ja gut von github ziehen.

Leider muss noch eine weitere Stelle korrigiert werden.

In der Datenbank-Tabelle "tl_module" wird das Feld "filter_tags" noch mit 255 Zeichen geführt. Dort müssten die 1000 Zeichen auch geändert werden.

**Comment by hschottm** [comment]
Ähm, ich hab extra alles durchsucht, da ist nichts mehr mit 255 Zeichen. Es gibt auch kein Feld filter_tags in tl_module, wo siehst du das?

**Comment by AgentCT** [comment]
Bei mir steht das Feld in der <b>Datenbank</b>.

Dieses Feld war nur 255 Zeichen lang und nach meiner Änderung auch 1000 Zeichen speichert er die Eingaben vollständig.

![datenbankfeld zu klein](https://cloud.githubusercontent.com/assets/1218347/12079985/a31dec12-b24c-11e5-8cb0-d98beac86982.jpg)

**Comment by hschottm** [comment]
Ok, tag_filter. Aber das habe ich doch mit den beiden letzten Updates geändert. Hast du evtl. einfach nur die Quelldateien aktualisiert und nicht "Datenbank aktualisieren" in der Erweiterungsverwaltung aufgerufen? Das muss man natürlich schon machen, wenn es Änderungen an Datenbankfeldern gegeben hat. Sowohl in tl_module als auch in tl_content habe ich die tag_filter-Felder auf 1000 Zeichen angehoben.
