### ISSUE TITLE
Contao 4-Kompatibilität

### ISSUE THREAD

**Issue by Xendiadyon** [hschottm/tags#25]
Die Erweiterung ist (mit kleinen Einschränkungen #24 ) Contao4 (getestet mit Contao 4.2.3 und 4.3.0) kompatibel und die Anzeige der Tags sowie die Tag-Cloud funktioniert hervorragend. Über die Verwendung der weiteren Module kann ich keine Aussagen treffen.

Ich würde mich freuen, wenn die Erweiterung mit Bundle.php usw. in den Composer aufgenommen wird.

**Comment by Xendiadyon** [comment]
Anmerkung: Es gibt in Contao 4.3 Änderungen in der dca. Hier haben wir Überlagerungen der einzelnen Elemente im Backend. Hier müsste auch unbedingt noch mal reingegriffen werden und die class "clr" für einige Elemente hinzugefügt werden.

**Comment by m-vo** [comment]
Gibt es hier mittlerweile schon Neuigkeiten? Oder evtl. einen 4er-Fork

**Comment by Xendiadyon** [comment]
[tags_php7_contao4.zip](https://github.com/hschottm/tags/files/1148421/tags_php7_contao4.zip)

Was ich dir anbieten kann ist, meine aktuelle Version mal hochzuladen. Benutzung auf eigene Gefahr; es kann sein, dass es funktioniert, es kann aber auch sein dass da nichts läuft. Generell müsstest du 

Eigentlich wäre hier mal eine gewissenhafte Renovierung (Stichwort Responsives Layout in der dca) und Ergänzen der Bundle.php mit anschließender Aufnahme in den Composer nötig. Ist nicht allzu viel Arbeit, aber bei mir ist das zeitlich momentan nicht drin.

**Comment by m-vo** [comment]
Danke @Xendiadyon .

@hschottm - wie ist denn dein Plan für die Extension? Ich könnte, falls das für dich/euch in Ordnung ist, ein Repo basierend auf den Daten von @Xendiadyon aufmachen und schauen, ob sich mit überschaubarem Aufwand ein funktionierendes Bundle draus bauen lässt (& das dann auf Packagist hinzufügen).

**Comment by hschottm** [comment]
Ich schau mir das mal an, habe mich mit Contao 4 noch überhaupt nicht auseinander gesetzt.

**Comment by hschottm** [comment]
Ich habe jetzt erst mal eine "Billigvariante" mit composer-Unterstützung herausgebracht, die sich unter Contao 4.4.x installieren lassen sollte und die dortigen Besonderheiten schon einmal unterstützt. 

php composer.phar require hschottm/tags
