### ISSUE TITLE
Listbycategory imageUrl empty

### ISSUE THREAD

**Issue by MrFastDie** [hschottm/tags#29]
Why listing the articles with the provided tag the this->news elements does not contain the image of the news article.

    <?php foreach ($this->news as $article):
    var_dump($article); ?>

creates at the important part

    ["imagemargin"]=>string(98) "a:5 {s:6:"bottom";s:0:"";s:4:"left";s:0:"";s:5:"right";s:0:"";s:3:"top";s:0:"";s:4:"unit";s:0:"";}"
    ["imageUrl"]=> string(0) ""`

**Comment by MrFastDie** [comment]
#30

**Comment by hschottm** [comment]
Fixed by merging pull request bc329503c77427e3424658b53eb277d2ac69d9ad
