### ISSUE TITLE
Multi day event not visible

### ISSUE THREAD

**Issue by Teetrinker** [hschottm/tags#31]
The Contao core module had the problem that multi-day events were not visible in a list of future events. That was the case for a few version, but is fixed now (compare [https://github.com/contao/core/issues/8497](https://github.com/contao/core/issues/8497) )

I updated my installation to 3.5.27 to get rid of this problem. Nevertheless, an ongoing event is not shown.
The event list has a tag filter which contains the tag the said event is marked with.
If I deactivate the tags extension, the event is visible.

## Same in German:

Das Contao-Core-Calendar-Modul hatte das Problem, dass mehrtägige Events in einer Liste der zukünftigen Events ein paar Versionen lang nicht angezeigt wurden. Das ist nun behoben. (vergleiche Github: https://github.com/contao/core/issues/8497)
Ich habe meine Installation entsprechend auf 3.5.27 upgedated. Trotzdem wird ein laufender Termin nicht angezeigt.

Die Eventliste hat einen Auszeichnungs-Filter, dieser entspricht der Auszeichnung die die Veranstaltung hat.
Deaktiviere ich die Tags-Erweiterung, wird der Event angezeigt.

**Comment by hschottm** [comment]
Should be fixed with a2f66067b004da38167dd0f9b32499772d6e48a8

**Comment by Teetrinker** [comment]
Tested. Working. Thank you! 🙏
