### ISSUE TITLE
PHP 7 Kompatibilität

### ISSUE THREAD

**Issue by akroii** [hschottm/tags#34]
Ist die Erweiterung tags schon PHP7 fähig?

**Comment by akroii** [comment]
Sorry, dass ich nocheinmal nachfrage. Aber eine Info wäre sehr nützlich.

**Comment by Teetrinker** [comment]
Ja.

https://github.com/hschottm/tags/releases/tag/3.5

**Comment by hschottm** [comment]
Wird hiermit geschlossen
