### ISSUE TITLE
Contao 4.4: Error with gallery

### ISSUE THREAD

**Issue by jankout** [hschottm/tags#37]
Your extensions causes an error when the gallery is used. See [here](https://clevere-staedte.de/blog/artikel/weltweiter-parkingday-straßenaktivisten-machen-auf-lebenswertere-städte-und-die-park-gefahren-aufmerksam).

**Comment by hschottm** [comment]
Fixed in c2ab2ab7f52badb40dafb2ef9b8b9160ab908d3a
