### ISSUE TITLE
Fehler 500 statt 404

### ISSUE THREAD

**Issue by derastronaut** [hschottm/tags#38]
Hallo,

unter Contao 3.5 kam bei einem nicht vorhandenen Event noch ein 404-Fehler Seit 4.4 kommt Fehler 500 (laut Google). Zu sehen bekommt man unter 4.4 eine weiße Seite, unter 4.5 kommt die Fehlerseite von Contao selbst.

In den Logs steht:

`[2018-01-20 09:31:46] app.CRITICAL: An exception occurred. {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ClassNotFoundException(code: 0): Attempted to load class \"PageNotFoundException\" from namespace \"Contao\".\nDid you forget a \"use\" statement for \"Contao\\CoreBundle\\Exception\\PageNotFoundException\"? at /www/htdocs/wurst/contao/vendor/hschottm/tags/modules/ModuleEventReaderTags.php:32)"} []`

Gruß
Sebastian

**Comment by hschottm** [comment]
Fixed in 3861fd34585bf079acae767c11127c0da198eb26 and 257964d27d630526505f97dba98bcd5d1a1b315f
