### ISSUE TITLE
Contao 4.6: Internal Server Error 500 (Debug-Mode)

### ISSUE THREAD

**Issue by derastronaut** [hschottm/tags#44]
Nach dem Update von Contao 4.5.x auf 4.6 erhalte ich im Debug-Modus (app_dev.php) einen Internal Server Error 500:

`request.CRITICAL: Uncaught PHP Exception ErrorException: "Warning: Cannot declare class ModuleArticle, because the name is already in use" at /www/htdocs/w123456/contao/vendor/contao/core-bundle/src/Resources/contao/library/Contao/ClassLoader.php line 180 {"exception":"[object] (ErrorException(code: 0): Warning: Cannot declare class ModuleArticle, because the name is already in use at /www/htdocs/w123456/contao/vendor/contao/core-bundle/src/Resources/contao/library/Contao/ClassLoader.php:180)"} []`

Ich habe nach und nach alle Fremd-Erweiterungen (4 insgesamt) deinstalliert, um herauszufinden, welche Erweiterung den Fehler verursacht. Nach der Deinstallation von "Tags" geht die Seite wieder und die Fehlermeldung tauchte ab diesem Zeitpunkt nicht mehr in den Logs auf.

Hier noch ein Screenshot:
![2018-08-23_error-500](https://user-images.githubusercontent.com/5235594/44665734-f159d980-aa16-11e8-8233-36b1129817d8.png)

**Comment by havutcuoglu** [comment]
Hallo @hschottm ,

hierfür habe ich folgende Änderungen durchgeführt, damit die Erweiterung unter Contao 4.6 läuft.

1. /tags/modules/ModuleArticle.php die Zeile 3 und 13 angepasst.
Den Namespace von **Aurealis** umbenannt auf **Contao** und den Classennamen von **ModuleArticle** auf **ModuleArticleTags**. Ich weiß nicht, ob der Namespace Aurealis bleiben muss oder Vergessen wurde umzubenennen.

2. /tags/config/autoload.php die Zeile 50 angepasst.
`'Aurealis\ModuleArticle'         => 'system/modules/tags/modules/ModuleArticle.php',`
geändert auf 
`'Contao\ModuleArticleTags'         => 'system/modules/tags/modules/ModuleArticle.php',`

3. /tags/dca/tl_content.php die Zeile 18 erweitert und habe folgende Abfrage integriert.
`if (strlen($GLOBALS['TL_DCA']['tl_content']['palettes'][$key]) < 2)
{
    $pos = false;
}
else
{
    $pos = strpos($GLOBALS['TL_DCA']['tl_content']['palettes'][$key], '{', 2);
}`

Somit habe ich erstmal die Seite in Debug-Modus zum laufen gebracht.
Ich werde hier weiter berichten, wenn ich mit weiteren Problemen konfrontiert werde.
Ansonsten kannst du die Änderungen eventuell mit in die Repo aufnehmen.

**Comment by havutcuoglu** [comment]
Hallo @hschottm ,
was mir noch aufgefallen ist, das in der **config.php** die **Zeile 109**
`$GLOBALS['TL_FFL']['tag'] = 'TagFieldMemberFrontend';`
in die Formularfelder einen Select-Option hinzugefügt wird. Diese hat aber keinen Inhalt und wurde in den Language Files nicht übersetzt.
Sollte vielleicht im Zuge mit geprüft werden, ob dies noch relevant ist.

Herzliche Grüße

**Comment by hschottm** [comment]
Fixed in f97eceb8b6b86adc64a385c6a8775ca3b5e55092

**Comment by matthiasprieth** [comment]
@hschottm thanks so much! :)
