### ISSUE TITLE
Warning: Use of undefined constant ENCODE_AMPERSANDS - assumed 'ENCODE_AMPERSANDS'

### ISSUE THREAD

**Issue by markush2** [hschottm/tags#46]
Hallo.

Ich bekomme für diese Erweiterung unter Contao 3.5.36 php7.2 die untenstehende Fehlermeldung.

Hier hatte ich es in die Contao Community eingestellt:
https://community.contao.org/de/showthread.php?72956-Nach-Umstellung-auf-php7-2-gibt-News-die-Fehlermeldung-Warning-Use-of-undefined-cons&p=490373#post490373

[CODE]
Warning: Use of undefined constant ENCODE_AMPERSANDS - assumed 'ENCODE_AMPERSANDS' (this will throw an Error in a future version of PHP) in system/modules/tags/modules/ModuleTagCloud.php on line 95
#0 system/modules/tags/modules/ModuleTagCloud.php(95): __error(2, 'Use of undefine...', '/home/www/evtf....', 95, Array)
#1 system/modules/tags/modules/ModuleTagCloud.php(86): Contao\ModuleTagCloud->showTags()
#2 system/modules/core/modules/Module.php(287): Contao\ModuleTagCloud->compile()
#3 system/modules/tags/modules/ModuleTagCloud.php(78): Contao\Module->generate()
#4 system/modules/core/elements/ContentModule.php(59): Contao\ModuleTagCloud->generate()
#5 system/modules/core/library/Contao/Controller.php(484): Contao\ContentModule->generate()
#6 system/modules/core/modules/ModuleArticle.php(213): Contao\Controller::getContentElement(Object(Contao\ContentModel), 'main')
#7 system/modules/tags/modules/ModuleArticle.php(26): Contao\ModuleArticle->compile()
#8 system/modules/core/modules/Module.php(287): Aurealis\ModuleArticle->compile()
#9 system/modules/core/modules/ModuleArticle.php(67): Contao\Module->generate()
#10 system/modules/core/library/Contao/Controller.php(417): Contao\ModuleArticle->generate(false)
#11 system/modules/core/library/Contao/Controller.php(277): Contao\Controller::getArticle(Object(Contao\ArticleModel), false, false, 'main')
#12 system/modules/core/pages/PageRegular.php(133): Contao\Controller::getFrontendModule('0', 'main')
#13 system/modules/core/controllers/FrontendIndex.php(285): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#14 index.php(20): Contao\FrontendIndex->run()
#15 {main}

Warning: Cannot modify header information - headers already sent by (output started at /home/www/evtf.eu/system/helper/functions.php:65) in system/modules/core/library/Contao/Template.php on line 294
#0 [internal function]: __error(2, 'Cannot modify h...', '/home/www/evtf....', 294, Array)
#1 system/modules/core/library/Contao/Template.php(294): header('Vary: User-Agen...', false)
#2 system/modules/core/classes/FrontendTemplate.php(121): Contao\Template->output()
#3 system/modules/core/pages/PageRegular.php(190): Contao\FrontendTemplate->output(true)
#4 system/modules/core/controllers/FrontendIndex.php(285): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#5 index.php(20): Contao\FrontendIndex->run()
#6 {main}

Warning: Cannot modify header information - headers already sent by (output started at /home/www/evtf.eu/system/helper/functions.php:65) in system/modules/core/library/Contao/Template.php on line 295
#0 [internal function]: __error(2, 'Cannot modify h...', '/home/www/evtf....', 295, Array)
#1 system/modules/core/library/Contao/Template.php(295): header('Content-Type: t...')
#2 system/modules/core/classes/FrontendTemplate.php(121): Contao\Template->output()
#3 system/modules/core/pages/PageRegular.php(190): Contao\FrontendTemplate->output(true)
#4 system/modules/core/controllers/FrontendIndex.php(285): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#5 index.php(20): Contao\FrontendIndex->run()
#6 {main}[/CODE]

**Comment by hschottm** [comment]
Fixed in 45464754c441b60031ff54ebafeffd5624aaa405
