### ISSUE TITLE
Leerzeichen Fehler

### ISSUE THREAD

**Issue by Dani79** [hschottm/tags#49]
Sobald ich ein Tag anlege zb.: CMS Contao, was eine Leerzeichen hat, erzeigt er eine falsche url.

/tag/CMS%2520Contao.html

Somit wird dann auch nicht gefiltert, und es werden alle Ergebnisse ausgespuckt.

**Comment by FrischBlau** [comment]
Ich habe das gleiche Thema in frischen Contao-Installationen bzw. in Installationen, die auf Contao 4.4.41 aktualisiert wurden. In Release 4.0.10 gibt es das Problem noch nicht, erst ab 4.0.11. Außer Leerzeichen betrifft es auch Tags mit Umlauten. Über einen Fix, gern auch kostenpflichtig, würde ich mich freuen, da die Tags-Erweiterung im aktuellen Zustand nicht verwendbar ist.

**Comment by GMTeams** [comment]
Kann ich ebenfalls bestätigen, Contao 4.4.39.

**Comment by hschottm** [comment]
Die Sonderzeichen wurden doppelt URL-encodiert, einmal in der Erweiterung und dann noch einmal in generateFrontendUrl, behoben in 416a31e1dae4adbaf584b1ecfcd4ba773f2bd063
