### ISSUE TITLE
Contao 4.7: Tagliste (news_full_tags.hmtl5) zeigt keine Tags

### ISSUE THREAD

**Issue by k-webdesign** [hschottm/tags#50]
Hallo,

wenn ich unter Contao 4.7 news_full_tags.html5 einbinde, werden die Tags nicht gelistet. Die Variable ist leer, obwohl sie im Backend prall gefüllt ist: "showTags" => "".
Die Tags liefen noch in der 3.5.

Wird diese Erweiterung noch weiter supported?

**Comment by hschottm** [comment]
Also ich habe es mit Contao 4.8 probiert und konnte die Tags auflisten lassen. Ich habe allerdings auch eine neue Version von tags auf Packagist eingestellt, ich vermute, dass das Problem dadurch behoben wurde.
