### ISSUE TITLE
Contao 4.8: Auflistung dazugehöriger News funktioniert nicht

### ISSUE THREAD

**Issue by jankout** [hschottm/tags#51]
Hallo, 

seit 4.8.x habe ich gemerkt, dass die Auflistung dazugehöriger News nicht funktioniert. Wie kann ich diesen Fehler beheben? 

Siehe https://www.allesbrille-berlin.com/tags/tag/KOMONO

Schon jetzt danke ich dir für deine Antwort und wünsche dir noch einen schönen Tag.

**Comment by jankout** [comment]
Und wenn ich auf das Modul für den Tag-Cloud klicke, um ihn im Backend zu bearbeiten, erscheint folgende Fehlermeldung: 

`Argument 2 passed to Contao\Controller::getTemplateGroup() must be of the type array, string given, called in /homepages/35/d432404500/htdocs/contao4/var/cache/prod/contao/dca/tl_module.php on line 2570`

**Comment by fritzmg** [comment]
Selbes Problem wie [hier](https://github.com/fritzmg/contao-sharebuttons/issues/41) und [hier](https://community.contao.org/de/showthread.php?76082-Contao-Controller-getTemplateGroup()-erwartet-Array-als-2-Parameter).

**Comment by jankout** [comment]
@fritzmg Danke dir. Leider kenne ich mich bei dieser Erweiterung nicht so gut aus, um es selber zu korrigieren. Ich vermute, dass ich im Ordner classes/ schauen müsste. Weißt du vielleicht, um welche Stelle es sich handelt?

**Comment by fritzmg** [comment]
https://github.com/hschottm/tags/blob/45464754c441b60031ff54ebafeffd5624aaa405/dca/tl_module.php#L58

https://github.com/hschottm/tags/blob/45464754c441b60031ff54ebafeffd5624aaa405/dca/tl_module.php#L68

https://github.com/hschottm/tags/blob/45464754c441b60031ff54ebafeffd5624aaa405/dca/tl_module.php#L78

https://github.com/hschottm/tags/blob/45464754c441b60031ff54ebafeffd5624aaa405/dca/tl_module.php#L88

**Comment by jankout** [comment]
@fritzmg Vielen Dank. Dann einfach ohne `, $dc->activeRecord->pid`. 
D.h. `return $this->getTemplateGroup('mod_');`

**Comment by fritzmg** [comment]
Genau, ja. Den zweiten Parameter einfach entfernen.

**Comment by jankout** [comment]
@fritzmg Wunderbar. Deine Hilfe war wieder perfekt. Mit dem Modul hat es nun geklappt. 

Allerdings geht noch nicht die Auflistung der zugehörigen News, wenn ich auf eines der Schlagwörter klicke.

**Comment by hschottm** [comment]
Fixed in 762071795f9c2675a709c425bc79a539e3fdd557

**Comment by jankout** [comment]
Hallo, 

Kamil already fixed it because we didn’t have any respond from you. See his work.
