### ISSUE TITLE
Sonderzeichen (Umlaute) im {{used_tags}}

### ISSUE THREAD

**Issue by arboc** [hschottm/tags#52]
Wir haben Tags mit Umlauten.   
Wenn wir das Insterttag  `{{used_tags}}` verweden, werden die Umlaute codiert angezeigt, 

Bsp: **Frühstück** wird zu **Fr%C3%BChst%C3%BCck**

**Comment by hschottm** [comment]
Fixed in 416a31e1dae4adbaf584b1ecfcd4ba773f2bd063
