### ISSUE TITLE
Blockierung zwei Funktionen für das Weiterleitungsziel bei Events und News

### ISSUE THREAD

**Issue by jankout** [hschottm/tags#53]
Hallo Heinrich, 

leider blockiert deine Erweiterung zwei Funktionen unter _**Weiterleitungsziel**_ bei News und Events. So ist es nicht möglich, Links für **_Seiten_** und **_Individuelle URL_** zu setzen. 

Meine Beschreibung findest du auch in [Contao-Forum](https://community.contao.org/de/showthread.php?76272-Blockierung-zwei-Funktionen-für-das-Weiterleitungsziel-bei-Events-und-News&p=513186#post513186). 

Ich gehe davon aus, dass dein Javascript mit dem von Contao nicht klarkommt. 

Da diese Funktionen sehr wichtig sind und für den Nutzer funktionieren sollen, möchte ich dich bitten, das so schnell wie möglich zu beheben. Gerne kannst du mir auch eine Lösung schicken und ich mache es selber. Das wäre toll. 

Ich danke dir schon jetzt im Voraus für deine Hilfe. 

Liebe Grüße,
Jan

**Comment by hschottm** [comment]
Fixed in 936be13afd5fddaea9fcd11e5ff123f0bc1c6e3f
