### ISSUE TITLE
Version 5.0 / 4.0.21

### ISSUE THREAD

**Issue by Sioweb** [hschottm/tags#62]
Hallo @hschottm o/

wäre es möglich, das PR von mir in eine höhere Version zu schieben?

5.0.0, oder 4.1.0? 

Die Funktionen StrinUtil::ampersand bspw. gibt es erst seit Contao 4.10. So kann das Modul für 4.10 & < 4.10 entwickelt werden, ohne dass alle < 4.10 Instanzen nicht mehr funktionieren.

`Attempted to call an undefined method named "ampersand" of class "Contao\StringUtil`

Ansonsten kann ich auch gerne die `deprecated` Funktionen wieder in den Code einfügen.

Danke & LG
Sascha

**Comment by hschottm** [comment]
Verdammt, ich dachte ich hätte das verpennt und schon viel eher mal umstellen müssen. Dann muss ich das schnell ändern, hab ich natürlich auch nicht getestet...

**Comment by hschottm** [comment]
So, ich habe jetzt für jede Contao-Version ab 4.4 eine eigene Versionnummer das Paketes erstellt, weil ich in den Klassen ModuleEventListTags und ModuleEventReaderTags leider Contao-Funktionen aus ModuleEventList und ModuleEventReader "duplizieren" muss und an einigen Stellen verändern muss und diese Funktionen sind für jede Contao-Version seit 4.4. immer ein bisschen anders. Die 4.0.x Versionen von tags sind für Contao 4.4, die 4.1.x Versionen von tags sind für Contao 4.5 usw. Für Contao 4.10 habe ich jetzt noch die Version 4.6.0 erstellt.
Ich habe mal geschaut, es war glaube ich nur die Funktion StringUtil::ampersand die für die alten Contao-Versionen wieder ausgetauscht werden musste. Die generateFrontEndUrl-Funktionen im PageModel gibt es mindestens schon seit Contao 4.4, das sollte also nicht krachen, StringUtil::specialchars ebenso.
