### ISSUE TITLE
4.5.1 nicht unter Contao 4.9. installierbar

### ISSUE THREAD

**Issue by johannes-bittner** [hschottm/tags#66]
Unter 4.5 funktioniert die Weiterleitung auf die tags-Seite nicht (mehr). 4.5.1 lässt sich aber nicht über den Manager installieren: 

> hschottm/tags 4.5.1 requires contao/core-bundle ~4.10 -> satisfiable by contao/core-bundle[4.10.0].

**Comment by hschottm** [comment]
Ja, sorry, ich bin mit dem Versionsmanagement durcheinander gekommen. Diese Versionen sollten für Contao 4.10 sein und eigentlich 4.6.1 bzw. 4.6.2 werden. Ich werde gleich eine 4.5.3 nachschieben, die für Contao 4.9 ist und den Fehler hoffentlich behebt.

**Comment by hschottm** [comment]
So, nachdem ich es nun wieder geschafft hatte, einen Funktionsaufruf einzufügen, der nur in Contao 4.10 funktioniert, nun die endgültige aktuelle Version für Contao 4.9
Es handelt sich um die Tags-Version 4.5.4 basierend auf ef48b9040483f5a1e7ba686213361edfb78cb9dc

**Comment by johannes-bittner** [comment]
👍👍👍 you made my day

BTW: ABI LLS 87?

**Comment by hschottm** [comment]
Na klar Johannes, genau wie du :D
