### ISSUE TITLE
Kompatibilität Contao 4.9

### ISSUE THREAD

**Issue by operatorone** [hschottm/tags#71]
Hi, wenn ich versuche das Paket in Contao 4.9 zu installieren, bekomme ich folgende Fehler im Contao Manager:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install hschottm/tags 4.6.4
    - Conclusion: don't install hschottm/tags 4.6.3
    - Conclusion: don't install hschottm/tags 4.6.2
    - Conclusion: don't install hschottm/tags 4.6.1
    - Conclusion: remove contao-components/highlight 9.18.1
    - Installation request for hschottm/tags ^4.6 -> satisfiable by hschottm/tags[4.6.0, 4.6.1, 4.6.2, 4.6.3, 4.6.4].
    - Conclusion: don't install contao-components/highlight 9.18.1
    - hschottm/tags 4.6.0 requires contao/core-bundle ~4.10 -> satisfiable by contao/core-bundle[4.10.0, 4.10.1, 4.10.2, 4.10.3, 4.10.4].
    - contao/core-bundle 4.10.0 requires contao-components/highlight ^10.0 -> satisfiable by contao-components/highlight[10.0.0, 10.0.1, 10.0.2, 10.0.3, 10.1.0, 10.1.1, 10.1.2, 10.2.0, 10.2.1].
    - contao/core-bundle 4.10.1 requires contao-components/highlight ^10.0 -> satisfiable by contao-components/highlight[10.0.0, 10.0.1, 10.0.2, 10.0.3, 10.1.0, 10.1.1, 10.1.2, 10.2.0, 10.2.1].
    - contao/core-bundle 4.10.2 requires contao-components/highlight ^10.0 -> satisfiable by contao-components/highlight[10.0.0, 10.0.1, 10.0.2, 10.0.3, 10.1.0, 10.1.1, 10.1.2, 10.2.0, 10.2.1].
    - contao/core-bundle 4.10.3 requires contao-components/highlight ^10.0 -> satisfiable by contao-components/highlight[10.0.0, 10.0.1, 10.0.2, 10.0.3, 10.1.0, 10.1.1, 10.1.2, 10.2.0, 10.2.1].
    - contao/core-bundle 4.10.4 requires contao-components/highlight ^10.0 -> satisfiable by contao-components/highlight[10.0.0, 10.0.1, 10.0.2, 10.0.3, 10.1.0, 10.1.1, 10.1.2, 10.2.0, 10.2.1].
    - Can only install one of: contao-components/highlight[10.0.0, 9.18.1].
    - Can only install one of: contao-components/highlight[10.0.1, 9.18.1].
    - Can only install one of: contao-components/highlight[10.0.2, 9.18.1].
    - Can only install one of: contao-components/highlight[10.0.3, 9.18.1].
    - Can only install one of: contao-components/highlight[10.1.0, 9.18.1].
    - Can only install one of: contao-components/highlight[10.1.1, 9.18.1].
    - Can only install one of: contao-components/highlight[10.1.2, 9.18.1].
    - Can only install one of: contao-components/highlight[10.2.0, 9.18.1].
    - Can only install one of: contao-components/highlight[10.2.1, 9.18.1].
    - Installation request for contao-components/highlight (locked at 9.18.1) -> satisfiable by contao-components/highlight[9.18.1].

Ich könnte auch eine ältere Version installieren, würde aber natürlich gerne die aktuelle nutzen.

**Comment by hschottm** [comment]
Sie müssen auch keine ältere Version installieren, aber die tags-Versionen 4.6.x sind ausschließlich für Contao 4.10, während die 4.5.x-Versionen für Contao 4.9 sind. Die aktuelle tags-Version 4.5.5 ist genauso neu und auf dem gleichen Stand wie die Version 4.6.4, da tags aber, um bestimmte Funktionen bieten zu können teilweise Contao-Code wiederverwenden muss, gibt es unterschiedliche Versionsschienen für die Tags-Komponente. Die aktuelle 4.6.x ist für Contao 4.10 auf genau dem gleichen Stand wie die aktuelle 4.5.x für Contao 4.9 ist. Das hat also schon seinen Grund, dass die Kompatibilitätsangaben eine Installation der Version 4.6.x nicht unter Contao 4.9 erlauben, Sie würden sich das System zerschießen.

**Comment by operatorone** [comment]
Ah verstehe. Dann vielen Dank für den Hinweis und die passive Vorsichtmaßnahme :-)
