### ISSUE TITLE
Warning: Undefined array key "urlKeywords" in Debug modus

### ISSUE THREAD

**Issue by tsarma** [hschottm/tags#83]
Contao 4.13
Tags: 4.6.4
PHP: 8.1.5

Throws internal server error 500, when you enable debug mode in the backend.

![Screenshot 2022-05-19 at 13 49 16](https://user-images.githubusercontent.com/683894/169286794-e3862f0a-6879-48c3-b692-9cfe1a265527.png)

**Comment by hschottm** [comment]
Fixed in 55d341066cc5389e96c90d7e0c3f368d4e99c0b7
New version 4.9.0 is available for Contao 4.13 on packagist
