### ISSUE TITLE
PHP 8 - Uncaught PHP Exception TypeError: "join(): Argument #2 ($array) must be of type ?array, string given

### ISSUE THREAD

**Issue by pindo-bindo** [hschottm/tags#86]
Hallo,

unter PHP 8 wird folgender Fehler ausgegeben:

request.CRITICAL: Uncaught PHP Exception TypeError: "join(): Argument #2 ($array) must be of type ?array, string given" at /xxxx/vendor/hschottm/tags/classes/TagListNews.php line 82 {"exception":"[object] (TypeError(code: 0): join(): Argument #2 ($array) must be of type ?array, string given at /xxxx/vendor/hschottm/tags/classes/TagListNews.php:82)"} []

Unter PHP 7.4 lief alles noch problemlos.

In ein paar Wochen schon unterstützt der Hoster meines Kunden PHP 7.4 nicht mehr und schaltet auf PHP 8 um.

Contao Version 4.9.20 - Tags Version 4.5.5

Gibt es schon ein fix?

Besten Dank für die Hilfe!

**Comment by hschottm** [comment]
Hallo, bitte aktualisieren Sie auf tags 4.5.7, das ist die aktuelle Version für Contao 4.9 und dort sind auch einige PHP 8 Fehlermeldungen behoben.

**Comment by pindo-bindo** [comment]
Vielen vielen Dank!
Mit  tags v 4.5.7. läuft alles problemlos.
