### ISSUE TITLE
Contao 4.13.12: TagHelper.php Problem mit getFrontendUrl

### ISSUE THREAD

**Issue by Misco** [hschottm/tags#87]
request.CRITICAL: Uncaught PHP Exception Symfony\Component\ErrorHandler\Error\UndefinedMethodError: "Attempted to call an undefined method named "getFrontendUrl" of class "Contao\Model\Collection"." at /www/htdocs/w01795d8/c4/vendor/hschottm/tags/classes/TagHelper.php line 192 {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\UndefinedMethodError(code: 0): Attempted to call an undefined method named \"getFrontendUrl\" of class \"Contao\\Model\\Collection\". at /www/htdocs/w01795d8/c4/vendor/hschottm/tags/classes/TagHelper.php:192)"} []

hoffe es gibt einen einfachen fix =)

**Comment by hschottm** [comment]
Bestimmt, ich kümmere mich gleich daraum

**Comment by Misco** [comment]
so scheint es zu klappen: 

`$arrTags[$idx]['url'] = StringUtil::ampersand($pageObj->current()->getFrontendUrl('/tag/' . $tag['tag']));`

**Comment by hschottm** [comment]
Fixed in ef759f02354437ff2a52f966d07063efd939e793
