### ISSUE TITLE
Tag List by categorie

### ISSUE THREAD

**Issue by biowebfr** [hschottm/tags#90]
Contao 4.13.13
Tags 4.9.9
I've this warning when trying this module:

![image](https://user-images.githubusercontent.com/46192868/203974610-4636e0a4-34c3-4935-833b-966338172128.png)

I only added tags on News.

Module config : 
![image](https://user-images.githubusercontent.com/46192868/203974646-9473d42b-3bdd-4d72-b1d4-3e4540c35da8.png)

**Comment by hschottm** [comment]
Fixed in 006fef7feec456cfac80b77286d37324427724ed

**Comment by biowebfr** [comment]
Ok nice !

I've got a new one here : 
![image](https://user-images.githubusercontent.com/46192868/204537505-cfb0c3ac-15cd-40eb-a01d-7cd06ab742fd.png)
