### ISSUE TITLE
Warning: count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by biowebfr** [hschottm/tags#91]
Contao 4.13.13
Tags 4.9.10
Hello, I found 2 errors on these files.

![image](https://user-images.githubusercontent.com/46192868/205863879-46ef09ab-2db1-4ecc-8e00-28bc5fab1b53.png)
![image](https://user-images.githubusercontent.com/46192868/205863930-caee0554-7405-4969-ade5-f4a295c2f0de.png)

**Comment by hschottm** [comment]
Fixed in d9e1700293a884d87cc4973c473fef3392bcff40
