### ISSUE TITLE
Event Liste mit featured/hervorgehobenen Events

### ISSUE THREAD

**Issue by steve-smart** [hschottm/tags#92]
Ich möchte in einer Eventliste hervorgehobene (zukünftige) Events anzeigen lassen (Contao 4.13.14). Leider funktioniert das bei installierter Tags-Erweiterung (4.9.11) nicht. Die "hervorgehoben"-Einstellungen werden hier nicht berücksichtigt:
https://github.com/hschottm/tags/blob/master/modules/ModuleEventlistTags.php#L30
Hier müsste der Code bitte noch entsprechend angepasst werden.

**Comment by fritzmg** [comment]
> Hier müsste der Code bitte noch entsprechend angepasst werden.

Dies ist eine frei verfügbare Open Source Erweiterung. Du könntest dich ja direkt an den Vendor (oder anderen Entwickler per PR) wenden und dieses Feature entsprechend finanzieren.

**Comment by plorenz-etes** [comment]
> Dies ist eine frei verfügbare Open Source Erweiterung. Du könntest dich ja direkt an den Vendor (oder anderen Entwickler per PR) wenden und dieses Feature entsprechend finanzieren.

Es handelt sich bei diesem "Feature" um die Anpassung exakt einer Zeile von

```
$arrAllEvents = parent::getAllEvents($arrCalendars, $intStart, $intEnd);
```

zu

```
$arrAllEvents = parent::getAllEvents($arrCalendars, $intStart, $intEnd, $blnFeatured);
```

Ich denke nicht, dass dafür eine Finanzierung notwendig sein sollte :)

**Comment by hschottm** [comment]
Sorry, bin drüber weggekommen. Habe es jetzt behoben.
Fixed in 6301b7e9380aa4053565cdb9c845dc9e0f0ea1c2

**Comment by steve-smart** [comment]
Danke schön!
