### ISSUE TITLE
PHP Error Declaration of Contao\ContentGalleryTags must be compatible with Contao\Controller

### ISSUE THREAD

**Issue by schifflm** [hschottm/tags#93]
I have Contao 4.9 and tags 4.5.9 installed. When I try to edit a News entry I get the following error message:
Compile Error: Declaration of Contao\ContentGalleryTags::addImageToTemplate($template, array $rowData, $maxWidth = null, $lightboxGroupIdentifier = null, ?Contao\FilesModel $filesModel = null): void must be compatible with Contao\Controller::addImageToTemplate($objTemplate, $arrItem, $intMaxWidth = null, $strLightboxId = null, ?Contao\FilesModel $objModel = null)
in[ vendor/hschottm/tags/elements/ContentGalleryTags.php ](https://familienbewegung.de/_profiler/open?file=vendor/hschottm/tags/elements/ContentGalleryTags.php&line=81#line81)(line 81)

The ssame message is displayed, when I try to show the News entry in Frontend.

Thank you for your help.
Best Regards
Martin

**Comment by hschottm** [comment]
Please use tags 4.6.5 for Contao 4.9, it is the most actual version for Contao 4.9 and it shouldn't have this issue. I am currently a bit confused that tags 4.5 and 4.6 are for Contao 4.9, not sure what I did there, but tags 4.6 is definitely made for Contao 4.9 so an update to tags 4.6.5 should fix the issues that you are having with the error message. Feel free to reopen this report when it is not the case.

**Comment by schifflm** [comment]
Sorry, it's the same error with 4.6.5

**Comment by hschottm** [comment]
Fixed in 5abd8a4cabb59cc4400f27f40f6fc8c242e34035
Created a new release 4.6.6 for Contao 4.9

**Comment by schifflm** [comment]
> Fixed in [5abd8a4](https://github.com/hschottm/tags/commit/5abd8a4cabb59cc4400f27f40f6fc8c242e34035) Created a new release 4.6.6 for Contao 4.9

Thank you very much for the very quick correction !!!
Martin
