### ISSUE TITLE
Kompatibilität mit Contao 5.x

### ISSUE THREAD

**Issue by jankout** [hschottm/tags#94]
Hallo, 

ich möchte mich erkundigen, wann die Kompatibilität mit Contao 5.x kommt?

**Comment by hschottm** [comment]
Ich habe mir Contao 5 noch gar nicht angesehen, ich werde zusehen, dass ich das im Mai mal hinbekomme, im Moment bin ich dazu leider nicht in der Lage.

**Comment by jankout** [comment]
Hallo Helmut, ich möchte mich erkundigen, ob du demnächst für Contao 5.3 plants, das im Februar erscheinen wird?

**Comment by fritzmg** [comment]
@jankout if you are in need of development of this extension for Contao 5 you should probably either provide a PR yourself or finance either @hschottm or other developers to do it for you.

**Comment by mandrael** [comment]
Vielleicht könnten wir einen Spendenpool für den Entwickler einrichten für die Portierung von tags auf 5.3? Ich denke es haben viele Interesse daran, dass die Erweiterung auf 5.3 laufen wird. Vielleicht gubt es diese Funktion ja auf github.

**Comment by jankout** [comment]
@mandrael ich finde die Idee sehr gut, allerdings möchte ich etwas unterstützen, wenn ich sehe, dass hier auch immer wieder etwas gepflegt wird. Und das ist momentan nicht der Fall. Daher würde ich mir wünschen, dass wir erst mal das klären, damit ich Sicherheit habe, dass ich in etwas investiere, was weiter entwickelt wird. @hschottm

**Comment by hschottm** [comment]
Ich habe mir fest vorgenommen, mich in den nächsten Wochen mal mit den neuen Contao-Versionen auseinanderzusetzen. Eine regelmäßige Pflege der Komponenten kann ich leider nicht garantieren. Da ich die Erweiterung aber auch selbst einsetze und Demnächst wohl oder übel meine 4.13 LTS-Installationen aktualisieren muss, sollte der Leidensdruck da sein, Contao 5.3 zu unterstützen

**Comment by jankout** [comment]
> Ich habe mir fest vorgenommen, mich in den nächsten Wochen mal mit den neuen Contao-Versionen auseinanderzusetzen. Eine regelmäßige Pflege der Komponenten kann ich leider nicht garantieren. Da ich die Erweiterung aber auch selbst einsetze und Demnächst wohl oder übel meine 4.13 LTS-Installationen aktualisieren muss, sollte der Leidensdruck da sein, Contao 5.3 zu unterstützen

Das wäre toll. Vielen lieben Dank!

**Comment by hschottm** [comment]
So, ich habe gerade die initiale Version für Contao 5.3 erstellt. Alles ist neu, die Erweiterung ist jetzt ein Contao-Bundle, ich habe hoffentlich recht umfangreich getestet, sollten Problem auftreten, versuche ich, diese kurzfristig zu beheben

**Comment by jankout** [comment]
das finde ich großartig und bedanke mich sehr bei @hschottm!
