### ISSUE TITLE
Eventliste - Tags-Einstellungen im Frontend-Modul nicht bedienbar.

### ISSUE THREAD

**Issue by chrismchn** [hschottm/tags#95]
![Bildschirmfoto 2023-11-22 um 14 16 38](https://github.com/hschottm/tags/assets/84408084/32ad3b42-52f7-4b54-967e-18a754af8199)

Wenn das Contao Backend in der vollen Breite angezeigt wird, überlagern sich die Elemente im Abschnitt Tags-Einstellungen und man kann dann Ereignis-Auszeichnungen anzeigen nicht mehr deaktivieren.  Das Widget Weiterleigung zur Seite überlagert das dann.   In der einspaltigen Ansicht ist das dann nicht mehr.

**Comment by Teetrinker** [comment]
```
$GLOBALS['TL_DCA']['tl_module']['fields']['event_showtags']['eval']
    = array('submitOnChange'=>true, 'tl_class' => 'clr');
```
